=== faisal18/FS_WS_CURRENT/FS_WS_WSCTFW/SOAPUI_Calls/MemberRegistration/MemberRegister.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="http://www.eclaimlink.ae/DHD/ValidationSchema" elementFormDefault="qualified" version="2.0" id="MemberRegister" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:import schemaLocation="CommonTypes.xsd" namespace="http://www.eclaimlink.ae/DHD/ValidationSchema"/>
    <xs:element name="Member.Register">
 <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="1" name="Header">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="1" maxOccurs="1" name="SenderID" type="tns:HeaderSenderID" />
                            <xs:element minOccurs="1" maxOccurs="1" name="ReceiverID" type="tns:HeaderReceiverID" />
                            <xs:element minOccurs="1" maxOccurs="1" name="TransactionDate" type="tns:HeaderTransactionDate" />
                            <xs:element minOccurs="1" maxOccurs="1" name="RecordCount" type="tns:HeaderRecordCount" />
                            <xs:element minOccurs="1" maxOccurs="1" name="DispositionFlag" type="tns:HeaderDispositionFlag" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="Person">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="1" maxOccurs="1" name="FirstName" type="tns:PersonFirstName"/>
                            <xs:element minOccurs="0" maxOccurs="1" name="SecondName" type="tns:PersonSecondName"/>
                            <xs:element minOccurs="1" maxOccurs="1" name="FamilyName" type="tns:PersonFamilyName"/>
                            <xs:element minOccurs="0" maxOccurs="1" name="ContactNumber" type="tns:PersonContactNumber"/>
                            <xs:element minOccurs="1" maxOccurs="1" name="BirthDate" type="tns:PersonBirthDate"/>
                            <xs:element minOccurs="1" maxOccurs="1" name="Gender" type="tns:PersonGender"/>
                            <xs:element minOccurs="1" maxOccurs="1" name="Nationality" type="tns:PersonNationalityID"/>
                            <xs:element minOccurs="1" maxOccurs="1" name="PassportNumber" type="tns:PersonPassportNumber"/>
                            <xs:element minOccurs="1" maxOccurs="1" name="MaritalStatus" type="tns:PersonMaritalStatus"/>
                            <xs:element minOccurs="0" maxOccurs="1" name="Email" type="tns:PersonEmail"/>
                            <xs:element minOccurs="1" maxOccurs="1" name="Emirate" type="tns:PersonEmirate"/>
                            <xs:element minOccurs="1" maxOccurs="1" name="ResidentialLocation" type="tns:PersonResidentialLocation"/>
                            <xs:element minOccurs="1" maxOccurs="1" name="WorkLocation" type="tns:PersonWorkLocation"/>
                            <xs:element minOccurs="1" maxOccurs="1" name="Salary" type="tns:PersonSalary"/>
                            <xs:element minOccurs="1" maxOccurs="1" name="Commission" type="tns:PersonCommission"/>
                            <xs:element minOccurs="1" maxOccurs="1" name="EmiratesIDNumber" type="tns:MemberEmiratesIDNumber"/>
                            <xs:element minOccurs="1" maxOccurs="1" name="UIDNumber" type="tns:PersonUIDNumber"/>
                            <xs:element minOccurs="1" maxOccurs="1" name="Member">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="1" maxOccurs="1" name="ID" type="tns:MemberID"/>
                                        <xs:element minOccurs="1" maxOccurs="1" name="Relation" type="tns:MemberRelationEnum"/>
                                        <xs:element minOccurs="1" maxOccurs="1" name="RelationTo" type="tns:MemberRelationTo"/>
                                        <xs:element minOccurs="1" maxOccurs="unbounded" name="Contract">
                                            <xs:complexType>
                                                <xs:sequence>
                                                   <xs:element minOccurs="1" maxOccurs="1" name="PayerID" type="tns:PersonPayerID"/>
                                                    <xs:element minOccurs="1" maxOccurs="1" name="ProductOrigin" type="tns:ContractProductOrigin"/>
                                                    <xs:element minOccurs="1" maxOccurs="1" name="ProductCode" type="tns:ContractProductCode"/>
                                                    <xs:element minOccurs="1" maxOccurs="1" name="ProductID" type="tns:ContractProductID"/>
                                                    <xs:element minOccurs="1" maxOccurs="1" name="PolicyID" type="tns:ContractPolicyID"/>
                                                    <xs:element minOccurs="1" maxOccurs="1" name="EnrollmentDate" type="tns:ContractEnrollmentDate"/>
                                                    <xs:element minOccurs="1" maxOccurs="1" name="DeletionDate" type="tns:ContractDeletionDate"/>
                                                    <xs:element minOccurs="1" maxOccurs="1" name="GrossPremium" type="tns:ContractGrossPremium"/>
                                                    <xs:element minOccurs="1" maxOccurs="1" name="ActualPremium" type="tns:ContractActualPremium"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
										  <xs:element minOccurs="1" maxOccurs="1" name="Establishment">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element minOccurs="1" maxOccurs="1" name="EntityType" type="tns:EstablishmentEntityType"/>
                                                    <xs:element minOccurs="1" maxOccurs="1" name="EntityID" type="tns:EstablishmentEntityID"/>
                                                    <xs:element minOccurs="1" maxOccurs="1" name="ContactNumber" type="tns:EstablishmentContactNumber"/>
                                                    <xs:element minOccurs="1" maxOccurs="1" name="Email" type="tns:EstablishmentEmail"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== faisal18/FS_WS_CURRENT/FS_WS_WSCTFW/SOAPUI_Calls/MemberRegistration/Production-MemberRegister/E_1486.MR.TPA004.26-Jan-2016.From.INS044.To.DHA.XML
<?xml version="1.0" encoding="utf-8"?>
<Member.Register xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://www.eclaimlink.ae/DHD/ValidationSchema" xsi:noNamespaceSchemaLocation="http://www.eclaimlink.ae/DHD/ValidationSchema/MemberRegister.xsd">
  <Header>
    <SenderID>INS044</SenderID>
    <ReceiverID>DHA</ReceiverID>
    <TransactionDate>26/01/2016 13:47</TransactionDate>
    <RecordCount>119</RecordCount>
    <DispositionFlag>PRODUCTION</DispositionFlag>
  </Header>
  <Person>
    <FirstName>RAINA</FirstName>
    <SecondName>.</SecondName>
    <FamilyName>KHANAM</FamilyName>
    <ContactNumber></ContactNumber>
    <dateOfBirth>28/05/2003</dateOfBirth>
    <Gender>0</Gender>
    <Nationality>356</Nationality>
    <PassportNumber>J4262694</PassportNumber>
    <MaritalStatus>1</MaritalStatus>
    <Email></Email>
    <Emirate>1</Emirate>
    <ResidentialLocation>Error: Data Missing</ResidentialLocation>
    <WorkLocation>Error: Data Missing</WorkLocation>
    <Salary>4</Salary>
    <Commission>2</Commission>
    <EmiratesIDNumber>784-2003-8765083-9</EmiratesIDNumber>
    <UIDNumber>135933161</UIDNumber>
    <Member>
      <ID>44A2-AA18-2672-8210</ID>
      <Relation>3</Relation>
      <RelationTo>4506-6C13-4B59-9102</RelationTo>
      <Contract>
        <PayerID>INS044</PayerID>
        <ProductOrigin>4</ProductOrigin>
        <ProductCode>5553</ProductCode>
        <ProductID>Error: Data Missing</ProductID>
        <PolicyID>9531495054</PolicyID>
        <TopUpPolicy></TopUpPolicy>
        <EnrollmentDate>01/01/2016</EnrollmentDate>
        <DeletionDate>31/12/2016</DeletionDate>
        <GrossPremium>3000</GrossPremium>
        <ActualPremium>0</ActualPremium>
        <Establishment>
          <EntityType>Error: Data Missing</EntityType>
          <EntityID>Error: Data Missing</EntityID>
          <ContactNumber>Error: Data Missing</ContactNumber>
          <Email>Error: Data Missing</Email>
        </Establishment>
      </Contract>
    </Member>
  </Person>
  <Person>
    <FirstName>RITVIK</FirstName>
    <SecondName>.</SecondName>
    <FamilyName>RAJESH</FamilyName>
    <ContactNumber></ContactNumber>
    <dateOfBirth>09/04/2012</dateOfBirth>
    <Gender>1</Gender>
    <Nationality>356</Nationality>
    <PassportNumber>K4038043</PassportNumber>
    <MaritalStatus>1</MaritalStatus>
    <Email></Email>
    <Emirate>4</Emirate>
    <ResidentialLocation>Error: Data Missing</ResidentialLocation>
    <WorkLocation>Error: Data Missing</WorkLocation>
    <Salary>4</Salary>
    <Commission>2</Commission>
    <EmiratesIDNumber>784-2012-4036542-5</EmiratesIDNumber>
    <UIDNumber>119564983</UIDNumber>
    <Member>
      <ID>C507-6BEA-A48D-39D4</ID>
      <Relation>3</Relation>
      <RelationTo>08B1-A8DA-833D-5DEF</RelationTo>
      <Contract>
        <PayerID>INS044</PayerID>
        <ProductOrigin>4</ProductOrigin>
        <ProductCode>5569</ProductCode>
        <ProductID>Error: Data Missing</ProductID>
        <PolicyID>9539595072</PolicyID>
        <TopUpPolicy></TopUpPolicy>
        <EnrollmentDate>01/01/2016</EnrollmentDate>
        <DeletionDate>31/12/2016</DeletionDate>
        <GrossPremium>3822</GrossPremium>
        <ActualPremium>0</ActualPremium>
        <Establishment>
          <EntityType>Error: Data Missing</EntityType>
          <EntityID>Error: Data Missing</EntityID>
          <ContactNumber>Error: Data Missing</ContactNumber>
          <Email>Error: Data Missing</Email>
        </Establishment>
      </Contract>
    </Member>
  </Person>
  <Person>
    <FirstName>Jishil</FirstName>
    <SecondName>.</SecondName>
    <FamilyName>Surendran</FamilyName>
    <ContactNumber></ContactNumber>
    <dateOfBirth>25/01/1989</dateOfBirth>
    <Gender>1</Gender>
    <Nationality>356</Nationality>
    <PassportNumber>K7227143</PassportNumber>
    <MaritalStatus>2</MaritalStatus>
    <Email></Email>
    <Emirate>4</Emirate>
    <ResidentialLocation>Error: Data Missing</ResidentialLocation>
    <WorkLocation>Error: Data Missing</WorkLocation>
    <Salary>4</Salary>
    <Commission>2</Commission>
    <EmiratesIDNumber>Error: Data Missing</EmiratesIDNumber>
    <UIDNumber>124837089</UIDNumber>
    <Member>
      <ID>E5D6-636F-3F79-DFCA</ID>
      <Relation>1</Relation>
      <RelationTo>E5D6-636F-3F79-DFCA</RelationTo>
      <Contract>
        <PayerID>INS044</PayerID>
        <ProductOrigin>4</ProductOrigin>
        <ProductCode>3892</ProductCode>
        <ProductID>Error: Data Missing</ProductID>
        <PolicyID>5530302383</PolicyID>
        <TopUpPolicy></TopUpPolicy>
        <EnrollmentDate>11/01/2016</EnrollmentDate>
        <DeletionDate>31/05/2016</DeletionDate>
        <GrossPremium>1850</GrossPremium>
        <ActualPremium>0</ActualPremium>
        <Establishment>
          <EntityType>Error: Data Missing</EntityType>
          <EntityID>Error: Data Missing</EntityID>
          <ContactNumber>Error: Data Missing</ContactNumber>
          <Email>Error: Data Missing</Email>
        </Establishment>
      </Contract>
    </Member>
  </Person>
  <Person>
    <FirstName>Krishna</FirstName>
    <SecondName>.</SecondName>
    <FamilyName>Murthy Nagendra</FamilyName>
    <ContactNumber></ContactNumber>
    <dateOfBirth>18/02/1968</dateOfBirth>
    <Gender>1</Gender>
    <Nationality>356</Nationality>
    <PassportNumber>M5657086</PassportNumber>
    <MaritalStatus>2</MaritalStatus>
    <Email></Email>
    <Emirate>4</Emirate>
    <ResidentialLocation>Error: Data Missing</ResidentialLocation>
    <WorkLocation>Error: Data Missing</WorkLocation>
    <Salary>3</Salary>
    <Commission>2</Commission>
    <EmiratesIDNumber>Error: Data Missing</EmiratesIDNumber>
    <UIDNumber>7334549/2015/201(Error: Length exceeds maximum)</UIDNumber>
    <Member>
      <ID>55C3-A36F-3FAC-2FCA</ID>
      <Relation>1</Relation>
      <RelationTo>55C3-A36F-3FAC-2FCA</RelationTo>
      <Contract>
        <PayerID>INS044</PayerID>
        <ProductOrigin>4</ProductOrigin>
        <ProductCode>5188</ProductCode>
        <ProductID>GMD1115092</ProductID>
        <PolicyID>5537701707</PolicyID>
        <TopUpPolicy></TopUpPolicy>
        <EnrollmentDate>19/01/2016</EnrollmentDate>
        <DeletionDate>03/11/2016</DeletionDate>
        <GrossPremium>1950</GrossPremium>
        <ActualPremium>0</ActualPremium>
        <Establishment>
          <EntityType>Error: Data Missing</EntityType>
          <EntityID>Error: Data Missing</EntityID>
          <ContactNumber>Error: Data Missing</ContactNumber>
          <Email>Error: Data Missing</Email>
        </Establishment>
      </Contract>
    </Member>
  </Person>
  <Person>
    <FirstName>SHEELA</FirstName>
    <SecondName>.</SecondName>
    <FamilyName>SEBASTIAN MENACHERY</FamilyName>
    <ContactNumber></ContactNumber>
    <dateOfBirth>15/03/1969</dateOfBirth>
    <Gender>0</Gender>
    <Nationality>356</Nationality>
    <PassportNumber>M2305404</PassportNumber>
    <MaritalStatus>2</MaritalStatus>
    <Email></Email>
    <Emirate>4</Emirate>
    <ResidentialLocation>Error: Data Missing</ResidentialLocation>
    <WorkLocation>Error: Data Missing</WorkLocation>
    <Salary>4</Salary>
    <Commission>2</Commission>
    <EmiratesIDNumber>784-1969-1519860-8</EmiratesIDNumber>
    <UIDNumber>51660957</UIDNumber>
    <Member>
      <ID>97BD-B744-B2D8-0343</ID>
      <Relation>2</Relation>
      <RelationTo>9096-8AD3-3009-DCAD</RelationTo>
      <Contract>
        <PayerID>INS044</PayerID>
        <ProductOrigin>4</ProductOrigin>
        <ProductCode>5569</ProductCode>
        <ProductID>Error: Data Missing</ProductID>
        <PolicyID>9539595072</PolicyID>
        <TopUpPolicy></TopUpPolicy>
        <EnrollmentDate>01/01/2016</EnrollmentDate>
        <DeletionDate>31/12/2016</DeletionDate>
        <GrossPremium>4830</GrossPremium>
        <ActualPremium>0</ActualPremium>
        <Establishment>
          <EntityType>Error: Data Missing</EntityType>
          <EntityID>Error: Data Missing</EntityID>
          <ContactNumber>Error: Data Missing</ContactNumber>
          <Email>Error: Data Missing</Email>
        </Establishment>
      </Contract>
    </Member>
  </Person>
  <Person>
    <FirstName>Javid</FirstName>
    <SecondName>.</SecondName>
    <FamilyName>Ali</FamilyName>
    <ContactNumber></ContactNumber>
    <dateOfBirth>15/09/1985</dateOfBirth>
    <Gender>1</Gender>
    <Nationality>356</Nationality>
    <PassportNumber>Error: Data Missing</PassportNumber>
    <MaritalStatus>2</MaritalStatus>
    <Email></Email>
    <Emirate>Error: Data Missing</Emirate>
    <ResidentialLocation>Error: Data Missing</ResidentialLocation>
    <WorkLocation>Error: Data Missing</WorkLocation>
    <Salary>Error: Data Missing</Salary>
    <Commission>2</Commission>
    <EmiratesIDNumber>Error: Data Missing</EmiratesIDNumber>
    <UIDNumber>Error: Data Missing</UIDNumber>
    <Member>
      <ID>589A-B436-22FF-3852</ID>
      <Relation>1</Relation>
      <RelationTo>589A-B436-22FF-3852</RelationTo>
      <Contract>
        <PayerID>INS044</PayerID>
        <ProductOrigin>4</ProductOrigin>
        <ProductCode>3921</ProductCode>
        <ProductID>Error: Data Missing</ProductID>
        <PolicyID>5535702441</PolicyID>
        <TopUpPolicy></TopUpPolicy>
        <EnrollmentDate>08/06/2015</EnrollmentDate>
        <DeletionDate>07/06/2016</DeletionDate>
        <GrossPremium>3584.43</GrossPremium>
        <ActualPremium>0</ActualPremium>
        <Establishment>
          <EntityType>Error: Data Missing</EntityType>
          <EntityID>Error: Data Missing</EntityID>
          <ContactNumber>Error: Data Missing</ContactNumber>
          <Email>Error: Data Missing</Email>
        </Establishment>
      </Contract>
    </Member>
  </Person>
  <Person>
    <FirstName>PRIYANKA</FirstName>
    <SecondName>.</SecondName>
    <FamilyName>PRAKASH</FamilyName>
    <ContactNumber></ContactNumber>
    <dateOfBirth>21/04/1993</dateOfBirth>
    <Gender>0</Gender>
    <Nationality>356</Nationality>
